parameters:
    meta.home.title:        Becoming An Agile Architect - El blog Agil sobre coaching, Scrum, TDD y Continuous integration
    meta.home.description:  Un blog práctico sobre Agile Coaching, Scrum, Test Driven Development y cómo llevarlos a cabo mediante explicaciones claras y ejemplos de cada paso
    meta.home.keywords:     agile lean scrum kanban tdd extreme programming architect arquitectura clean code programacion coaching continuous integration integración continua

    emailing:
        contactNotification:
            template:       'PineipolBaaBundle:EmailTemplates:contact-form-notification.html.twig'
            fromAddress:    'alejandro.barba@becominganagilearchitect.com'
            toAddress:      'alejandro.barba@becominganagilearchitect.com'
            subject:        'Becoming An Agile Architect - Contact form request notification'

        contactUserResponse:
            template:       'PineipolBaaBundle:EmailTemplates:contact-form-user-response.html.twig'
            fromAddress:    'alejandro.barba@becominganagilearchitect.com'
            subject:        'Solicitud de contacto recibida - Becoming An Agile Architect'

        commentNotification:
            template:       'PineipolBaaBundle:EmailTemplates:comment-form-notification.html.twig'
            fromAddress:    'alejandro.barba@becominganagilearchitect.com'
            toAddress:      'alejandro.barba@becominganagilearchitect.com'
            subject:        'Becoming An Agile Architect - Comment form request notification'

        commentUserResponse:
            template:       'PineipolBaaBundle:EmailTemplates:comment-form-user-response.html.twig'
            fromAddress:    'alejandro.barba@becominganagilearchitect.com'
            subject:        'Comentario recibido - Becoming An Agile Architect'

    user:
        status:
            active:         'active'
            inactive:       'inactive'
            comment-user:   'comment-user'
            invalidated:    'invalidated'

    comment:
        status:
            new:            'new'
            validated:      'validated'
            denegated:      'denegated'
            retired:        'retired'
            