services:
    pineipol_baa.locale_listener:
        class: Pineipol\BaaBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    translation.loader.db:
        class: Pineipol\BaaBundle\Services\DbTranslationLoader
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: translation.loader, alias: db}

    pineipol_baa.routing_loader:
        class: Pineipol\BaaBundle\Services\TranslatedRoutesLoader
        arguments: [@session, @kernel]
        tags:
            - { name: routing.loader }

    pineipol_baa.email_service:
        class: Pineipol\BaaBundle\Services\EmailService
        arguments: ["@service_container"]

    pineipol_baa.comment_service:
        class: Pineipol\BaaBundle\Services\CommentService
        arguments: ["@service_container", @doctrine.orm.entity_manager]